pypowsybl.dynasim.pypowsyblDynamicModels = PyPowsybl Dynamic Models Supplier
pypowsybl.dynasim.pypowsyblEventModels = PyPowsybl Event Models Supplier
pypowsybl.dynasim.pypowsyblOutputVariables = PyPowsybl Output Variables Supplier
pypowsybl.dynasim.parameterCompletions = Parameter completions
pypowsybl.dynasim.parameterCompletion = Generator '${equipment}' given '${model}': set '${source}' completed as '${completed}', ${count} parameter(s) added
pypowsybl.dynasim.parameterAdded = ${parameter} = ${value}
